name: test

on: [push, pull_request]

env:
  CMAKE_FLAGS: -DCMAKE_CXX_FLAGS="-Werror" -DCMAKE_C_FLAGS="-Werror"

jobs:

  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt install liblua5.4-dev lua5.4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build ${{env.CMAKE_FLAGS}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: Build C Example
      working-directory: ${{github.workspace}}/examples/c
      run: |
        cmake -B build ${{env.CMAKE_FLAGS}}
        cmake --build build

    - name: Build C++ Example
      working-directory: ${{github.workspace}}/examples/cpp
      run: |
        cmake -B build ${{env.CMAKE_FLAGS}}
        cmake --build build

  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew install lua

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build ${{env.CMAKE_FLAGS}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Install
      run: sudo cmake --install ${{github.workspace}}/build

    - name: Build C Example
      working-directory: ${{github.workspace}}/examples/c
      run: |
        cmake -B build ${{env.CMAKE_FLAGS}}
        cmake --build build

    - name: Build C++ Example
      working-directory: ${{github.workspace}}/examples/cpp
      run: |
        cmake -B build ${{env.CMAKE_FLAGS}}
        cmake --build build

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt install doxygen liblua5.4-dev lua5.4
          pip install sphinx-rtd-theme Sphinx myst-parser

      - name: Build Docs
        run: |
          cmake -B ${{github.workspace}}/build
          cd build
          make doc

      - name: Archive Docs
        uses: actions/upload-artifact@v3
        with:
          name: archived-docs
          path: build/docs/_build
